# -*- coding: utf-8 -*-
"""Read rows from a master legend drawn in the Revit model.

A master legend holds the office standard for one category. Each row is:
the Type Mark text on the far left, then the graphic (filled region, detail
item, legend component, detail lines), then the description text.
Row detection is the pure function legend_library.rows_from_items.

Only these element kinds are read, because they copy cleanly between legend views:
text notes, filled regions, detail lines, legend components, detail components,
generic annotations and detail groups. Sub-elements (for example the boundary
lines of a filled region) are skipped, since they copy with their parent.
Dimensions are skipped: they depend on references that may not be copied.
"""

from legend_library import master_entry, rows_from_items
from units import mm_to_internal
from version_adapter import element_id_value, get_db

MARK_TOLERANCE_MM = 2.0

_ALLOWED_CATEGORIES = (
    "OST_TextNotes",
    "OST_LegendComponents",
    "OST_DetailComponents",
    "OST_GenericAnnotation",
    "OST_IOSDetailGroups",
    "OST_Lines",
)


def candidate_master_legends(doc):
    """Legend views that can be masters: not templates and not generated by this tool. Sorted by name."""
    from identity import read_view_payload
    DB = get_db()
    views = []
    for view in DB.FilteredElementCollector(doc).OfClass(DB.View):
        try:
            if view.IsTemplate or view.ViewType != DB.ViewType.Legend:
                continue
        except Exception:
            continue
        if read_view_payload(view):
            continue
        views.append(view)
    views.sort(key=lambda view: view.Name.lower())
    return views


def read_master(doc, legend_view):
    """Return (entries, notes) for a master legend. Entries are LibraryEntry rows with element ids."""
    DB = get_db()
    allowed = set()
    for name in _ALLOWED_CATEGORIES:
        built_in = getattr(DB.BuiltInCategory, name, None)
        if built_in is not None:
            allowed.add(element_id_value(DB.ElementId(built_in)))

    candidates = []
    collector = DB.FilteredElementCollector(doc).WherePasses(DB.ElementOwnerViewFilter(legend_view.Id))
    for element in collector.WhereElementIsNotElementType():
        if isinstance(element, DB.FilledRegion) or _category_value(element) in allowed:
            candidates.append(element)

    # Skip sub-elements such as a filled region's boundary lines: they copy with their parent.
    dependents = set()
    for element in candidates:
        try:
            for dependent_id in element.GetDependentElements(None):
                if element_id_value(dependent_id) != element_id_value(element.Id):
                    dependents.add(element_id_value(dependent_id))
        except Exception:
            continue

    items = []
    skipped = 0
    for element in candidates:
        identity = element_id_value(element.Id)
        if identity in dependents:
            continue
        box = None
        try:
            box = element.get_BoundingBox(legend_view)
        except Exception:
            box = None
        if box is None:
            skipped += 1
            continue
        is_text = isinstance(element, DB.TextNote)
        items.append({
            "id": identity,
            "is_text": is_text,
            "text": element.Text if is_text else "",
            "left": box.Min.X,
            "right": box.Max.X,
            "top": box.Max.Y,
            "bottom": box.Min.Y,
        })
    try:
        scale = float(legend_view.Scale) or 1.0
    except Exception:
        scale = 1.0
    rows, notes = rows_from_items(items, mm_to_internal(MARK_TOLERANCE_MM) * scale)
    if skipped:
        notes.append("{0} element(s) in '{1}' had no size and were ignored.".format(skipped, legend_view.Name))
    entries = []
    for index, row in enumerate(rows, 1):
        entry = master_entry(row, index)
        entry.master_view = legend_view
        entries.append(entry)
    return entries, notes


def _category_value(element):
    from version_adapter import element_id_value as _value
    category = getattr(element, "Category", None)
    if category is None:
        return None
    try:
        return _value(category.Id)
    except Exception:
        return None
